[LightDM]
user-authority-in-system-dir=true
run-directory=/run/lightdm
minimum-uid=1

[Seat:*]
pam-autologin-service=kernaid-rescue-ui-autologin
session-wrapper=/usr/lib/kernaid/rescue-ui-session-wrapper
user-session=kernaid-rescue-ui
autologin-user=kernaid-rescue-ui
autologin-user-timeout=0
autologin-session=kernaid-rescue-ui
allow-user-switching=false
allow-guest=false
greeter-hide-users=true
greeter-allow-guest=false
greeter-show-manual-login=false
greeter-show-remote-login=false
xserver-allow-tcp=false
xserver-command=X -extension DRI2 -extension DRI3 -extension XTEST
exit-on-failure=true
