import type { SessionDriver, StartSession, SessionInfo, EvidenceRequest, ArtifactRef, ReportFormat, SessionEvent } from "@kernaid/session-driver";
import type { Approval, DiagnosisProposal, Evidence, ExecutionEvent, SessionReport, ValidatedPlan } from "@kernaid/schemas";
import { OfflineRulesProvider } from "./fake-provider.js";
export class LocalSessionDriver implements SessionDriver {
 private readonly provider=new OfflineRulesProvider(); private evidence:Evidence[]=[]; private content=new Map<string,string>(); private sessions=new Map<string,StartSession>(); private sessionEvidence=new Map<string,Evidence[]>(); private proposals=new Map<string,DiagnosisProposal[]>(); private planSessions=new Map<string,string>(); private events=new Map<string,ExecutionEvent[]>();
 async startSession(input:StartSession):Promise<SessionInfo>{const id=`S-${crypto.randomUUID()}`;this.sessions.set(id,input);this.sessionEvidence.set(id,[]);this.proposals.set(id,[]);this.events.set(id,[]);return{id,state:"observe"};}
 async *sendUserPrompt(sessionId:string,prompt:string):AsyncIterable<SessionEvent>{this.assert(sessionId);yield{type:"status",message:"Analisi deterministica delle evidenze locali"};const records=(this.sessionEvidence.get(sessionId)??[]).map(evidence=>({evidence,content:this.content.get(evidence.id)??""}));const proposal=await this.provider.diagnose(prompt,records);this.proposals.get(sessionId)?.push(proposal);yield{type:"proposal",message:proposal.diagnosis,proposal};}
 async requestEvidence(sessionId:string,request:EvidenceRequest):Promise<Evidence[]>{this.assert(sessionId);const observedContent=request.observedContent??"fixture inventory";const bytes=new TextEncoder().encode(observedContent);const digest=await crypto.subtle.digest("SHA-256",bytes);const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");const item:Evidence={schemaVersion:"1.0",id:`E-${this.evidence.length+1}`,collector:request.collector,target:request.target,capturedAt:new Date().toISOString(),contentType:request.contentType??"text/plain",sha256:hash,sensitivity:"system",trust:"observed-untrusted",summary:request.summary??"Inventario raccolto in sola lettura",blobRef:`sha256:${hash}`};this.evidence.push(item);this.sessionEvidence.get(sessionId)?.push(item);this.content.set(item.id,observedContent);return[item];}
 async stagePlan(sessionId:string,proposal:DiagnosisProposal):Promise<ValidatedPlan>{const session=this.assert(sessionId);const plan:ValidatedPlan={schemaVersion:"1.0",planId:`P-${crypto.randomUUID()}`,targetFingerprint:session.targetFingerprint,diagnosis:proposal.diagnosis,evidenceIds:proposal.evidenceIds,risk:"R0",steps:[{action:"system.observe.noop",args:{},preconditions:["target.still_matches"],backup:"not-required",validation:"evidence.exists",rollback:null}]};this.planSessions.set(plan.planId,sessionId);return plan;}
 async approvePlan(_planId:string,_approval:Approval):Promise<void>{return;}
 async *executePlan(planId:string):AsyncIterable<ExecutionEvent>{const sessionId=this.planSessions.get(planId);if(!sessionId)throw new Error("unknown plan");const event:ExecutionEvent={schemaVersion:"1.0",planId,sequence:1,status:"succeeded",action:"system.observe.noop",message:"Evidenze presenti e piano R0 verificato; nessuna modifica eseguita",capturedAt:new Date().toISOString()};this.events.get(sessionId)?.push(event);yield event;}
 async *rollback(_planId:string):AsyncIterable<ExecutionEvent>{throw new Error("R0 plans do not mutate and require no rollback");}
 async exportReport(sessionId:string,format:ReportFormat):Promise<ArtifactRef>{const session=this.assert(sessionId);const events=this.events.get(sessionId)??[];const report:SessionReport={schemaVersion:"1.0",sessionId,targetFingerprint:session.targetFingerprint,facts:this.sessionEvidence.get(sessionId)??[],inferences:this.proposals.get(sessionId)??[],decisions:[],events,verification:events.some(event=>event.status==="succeeded")?"passed":"not-run",unresolvedRisks:["Nessuna riparazione è stata eseguita","Confermare la diagnosi con controlli mirati"]};const body=format==="json"?JSON.stringify(report,null,2):this.markdown(report);const mediaType=format==="json"?"application/json":"text/markdown";const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(body));const sha256=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");return{mediaType,uri:`data:${mediaType};charset=utf-8,${encodeURIComponent(body)}`,sha256};}
 private markdown(report:SessionReport):string{return `# KernAid report\n\nSession: ${report.sessionId}\n\n## Diagnosis\n\n${report.inferences.map(item=>item.diagnosis).join("\n\n")}\n\n## Evidence\n\n${report.facts.map(item=>`- ${item.id}: ${item.collector} — ${item.summary} (SHA-256 ${item.sha256})`).join("\n")}\n\n## Unresolved risks\n\n${report.unresolvedRisks.map(item=>`- ${item}`).join("\n")}\n`;}
 private assert(id:string):StartSession{const session=this.sessions.get(id);if(!session)throw new Error("unknown session");return session;}
}
